services:
  - type: web
    name: alphastack-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
    healthCheckPath: /health
    autoDeploy: true
